
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'checkout repo'

- script: 
   pwd
   npm install
   npx playwright install
   npx playwright test
  displayName: 'Exceute Playwright tests'
