
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'checkout repo'

- script: 
   npm install
   npx playwright install
   npm install dotenv
  displayName: 'Install playwright'

- script: 
   npx playwright test
  displayName: 'Execute playwright tests'