
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'checkout repo'

- script: 
   cd PLAYWRIGHT
   npm install
   npm init playwright@latest
   npm install dotenv
  displayName: 'Install playwright'

- script: 
   cd PLAYWRIGHT
   npx playwright test
  displayName: 'Execute playwright tests'