
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'checkout repo'

- script: 
   cd "PLAYWRIGHT"
   npm install
   npx playwright install
  displayName: 'Install playwright'

- script: 
   cd "PLAYWRIGHT"
   npm install dotenv
   npx playwright test
  displayName: 'Execute playwright tests'